# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
      - id: pyupgrade
        args: [--py37-plus]

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.2
    hooks:
      - id: flake8
        additional_dependencies:
          - 'flake8-print==4.0.1'

  - repo: https://github.com/pycqa/isort
    rev: 6.0.0
    hooks:
      - id: isort

  # Disable Prettier, TODO: use bash script
  # - repo: https://github.com/pre-commit/mirrors-prettier
  #   rev: v4.0.0-alpha.8
  #   hooks:
  #     - id: prettier
  #       types_or: [javascript]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        exclude: yarn.lock
        args:
          - -L
          - 'ro'
          - --ignore-words-list=OYU

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.20.1
    hooks:
      - id: eslint
        files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
        types: [file]
        additional_dependencies:
          - eslint
          - eslint-config-standard
          - eslint-plugin-import
          - eslint-plugin-jsdoc
          - eslint-plugin-n
          - eslint-plugin-prefer-arrow
          - eslint-plugin-promise
          - '@typescript-eslint/eslint-plugin'
        args: ['--fix']
